# Try to replicate this array without copying the numbers into an array

<div>
<img src="Exercise.png" width="400"/>
</div>

In [4]:
import numpy as np

In [9]:
a=np.ones((5, 5))
a[1:4, 1:4] = np.zeros((3, 3))
a[2, 2] = 9
print(a)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
