# Basics of NumPy

#### Why Numpy arrays run faster than python lists?

**It weights less than Python lists**

![Screenshot](screenshot.png)

**Numpy arrays are better organized, while python lists use pointers to locate it's scattered values**

![Screenshot2](screenshot2.png)

all images are from the free coding camp data analysis with python course https://www.freecodecamp.org/learn/data-analysis-with-python/numpy/what-is-numpy

***

In [2]:
import numpy as np

In [3]:
a=np.array([1,2,3], dtype=np.int16)
print(a)

[1 2 3]


In [4]:
b=np.array([[1.0,2.0,3.0],[4.0,5.0,6.0]], dtype=np.float16)
print(b)

[[1. 2. 3.]
 [4. 5. 6.]]


Number of dimensions

In [5]:
print(a.ndim)
print(b.ndim)

1
2


Number of (Columns, Rows)

In [6]:
print(a.shape)
print(b.shape)

(3,)
(2, 3)


In [7]:
print(a.dtype)
print(b.dtype)

int16
float16


Size in bytes of each item in the array

In [8]:
print(a.itemsize)
print(b.itemsize)

2
2


Size in bytes of the whole list

In [9]:
print(a.nbytes)
print(b.nbytes)

6
12


### Accesisng/Changing specified elements, rows, columns, etc

In [10]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


Get specific element

In [11]:
print(a[1,5])
print(a[1,-2])

13
13


Print especific row

In [12]:
print(a[0])
print(a[0,:])

[1 2 3 4 5 6 7]
[1 2 3 4 5 6 7]


print especific column

In [13]:
print(a[:,2])

[ 3 10]


Getting a little more fancy

In [14]:
#[startindex:endindex:stepsize]
print(a[0,1:6:2])
print(a[0,1:-1:2])

[2 4 6]
[2 4 6]


Change an especific value

In [15]:
a[1,5]=20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [16]:
#Change the values of a column
a[:,2]=[5]
print(a)
a[:,3]=[5,10]
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]
[[ 1  2  5  5  5  6  7]
 [ 8  9  5 10 12 20 14]]


3d example

In [17]:
b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [18]:
#Get specific element (work outside in)
#[set, row, column] or [set, row, column, element]
#Get 4
print(b[0,1,1])
#Get 7
print(b[1,1,0])
#Get set 2 row 2
print(b[1,1,:])

4
7
[7 8]


### Intializing diferent types of arrays

In [19]:
np.zeros((2,3), dtype=np.int16)

array([[0, 0, 0],
       [0, 0, 0]], dtype=int16)

In [20]:
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [21]:
#Any other number use full and specify the size of the array and the number
np.full((2,2), 99, dtype='int32')

array([[99, 99],
       [99, 99]], dtype=int32)

In [22]:
#Any other number (Full_like) use full and specify the size of the array and the number
np.full_like(a, 4)
#we are using the shape of a to create the array

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [23]:
#random decimal
np.random.rand(4,2)

array([[0.96188217, 0.74014269],
       [0.95263811, 0.3241438 ],
       [0.27578946, 0.44993393],
       [0.99948234, 0.18689713]])

In [24]:
#random integer values
np.random.randint(-4,8, size=(3,3)) #from -4 to 8

array([[-4, -1, -4],
       [-2,  3,  2],
       [-4, -3,  2]])

In [25]:
np.random.randint(10, size=(3,3))

array([[9, 2, 0],
       [1, 1, 7],
       [1, 0, 5]])

In [26]:
#random 3x3 identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
#random decimal with shape of a
np.random.random_sample(a.shape)

array([[0.29876767, 0.45192831, 0.53574311, 0.50575538, 0.06745677,
        0.55464063, 0.38657372],
       [0.14620525, 0.74718671, 0.08349229, 0.88428971, 0.03013324,
        0.26492961, 0.88749736]])

In [28]:
np.random.randint(10, size=a.shape)

array([[1, 7, 5, 9, 6, 4, 7],
       [9, 5, 3, 9, 5, 5, 9]])

In [29]:
# Repeat an array
arr=np.array([[1,2,3]])
r1=np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


##### **Copying arrays warning!!**

In [30]:
#If we want to copy an array don't use the equal sign
#Use the copy function
a=np.array([1,2,3])
b=a
b[0]=100
print(b)
print(a) #a will also change, because b is pointing to a, not copying it


[100   2   3]
[100   2   3]


In [31]:
a=np.array([1,2,3])
b=a.copy()
b[0]=100
print(b)
print(a) #a will not change

[100   2   3]
[1 2 3]


##### Linear Algebra

In [32]:
a = np.ones ((2,3), dtype=np.int16)
print(a)

b=np.full ((3,2), 2)
print(b)

np.matmul(a,b) #matrix multiplication

[[1 1 1]
 [1 1 1]]
[[2 2]
 [2 2]
 [2 2]]


array([[6, 6],
       [6, 6]])

In [33]:
c=np.identity(3)
print(c)
print(np.linalg.det(c)) #determinant
print(np.linalg.inv(c)) #inverse
print(np.linalg.eig(c)) #eigenvalues and eigenvectors

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
1.0
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
EigResult(eigenvalues=array([1., 1., 1.]), eigenvectors=array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]]))


##### Statistics

In [34]:
stats=np.array([[1,2,3],[4,5,6],[7,8,9]])  
print(stats)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [35]:
np.min(stats)

np.int64(1)

In [36]:
np.max(stats)

np.int64(9)

In [37]:
print(np.min(stats, axis=0)) #min of each column
print(np.min(stats, axis=1)) #min of each row

[1 2 3]
[1 4 7]


In [38]:
print(np.max(stats, axis=0)) #max of each column
print(np.max(stats, axis=1)) #max of each row

[7 8 9]
[3 6 9]


In [39]:
print(np.sum(stats)) #sum of all elements
print(np.sum(stats, axis=0)) #sum of each column
print(np.sum(stats, axis=1)) #sum of each row

45
[12 15 18]
[ 6 15 24]


##### Reorganizing Arrays

In [40]:
before = np.array([[1,2],[3,4],[5,6],[7,8]])
print(before)
print(before.shape)

after = before.reshape((2,4))   
print(after)
print(after.shape)

print(before.reshape((2,2,2))) #check the shape of the reshaped array

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
(4, 2)
[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [41]:
# Vertical stacking
a = np.array([[1,2,3,4]])
b = np.array([[5,6,7,8]])
c = np.vstack((a,b)) 
print(c)
# Horizontal stacking   
a = np.array([[1,2,3,4]])
b = np.array([[5,6,7,8]])
c = np.hstack((a,b))
print(c)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4 5 6 7 8]]


In [42]:
# You can stack multiple copies of the same array
a = np.array([[1,2,3]])
b = np.array([[5,6,7]])
c = np.vstack((a,b,b,a))
print(c)


[[1 2 3]
 [5 6 7]
 [5 6 7]
 [1 2 3]]


##### Import Data

In [56]:
#Load data without pandas using numpy

filedata= np.genfromtxt('data.txt', delimiter=',', dtype='int16')
print(filedata)

[[23 87 45 12 67 34 89 56 78 90]
 [11 32 76 54 98 21 43 65 88 29]
 [39 70 25 81 46 92 14 63 77 58]
 [19 84 31 50 72 96 28 41 66 93]
 [17 35 62 47 80 24 99 13 53 75]]


##### Advanced Indexing

#### Boolean Masking and Advanced Indexing

In [63]:
print((filedata>50),'\n')
print((filedata<=15), '\n')
print((filedata[filedata>50]), '\n')

[[False  True False False  True False  True  True  True  True]
 [False False  True  True  True False False  True  True False]
 [False  True False  True False  True False  True  True  True]
 [False  True False False  True  True False False  True  True]
 [False False  True False  True False  True False  True  True]] 

[[False False False  True False False False False False False]
 [ True False False False False False False False False False]
 [False False False False False False  True False False False]
 [False False False False False False False False False False]
 [False False False False False False False  True False False]] 

[87 67 89 56 78 90 76 54 98 65 88 70 81 92 63 77 58 84 72 96 66 93 62 80
 99 53 75] 



In [65]:
##You can index with a list in numpy
a=np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [66]:
np.any(filedata>50, axis=0) #check if any value in the column is greater than 50

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [ ]:
np.any(filedata>95, axis=1) #check if any value in the row is greater than 95

array([False,  True, False,  True,  True])

In [71]:
((filedata>50) & (filedata<67)) #check if any value in the column is greater than 50 and less than 67

array([[False, False, False, False, False, False, False,  True, False,
        False],
       [False, False, False,  True, False, False, False,  True, False,
        False],
       [False, False, False, False, False, False, False,  True, False,
         True],
       [False, False, False, False, False, False, False, False,  True,
        False],
       [False, False,  True, False, False, False, False, False,  True,
        False]])

## Index exercise

In [77]:
indexexer=np.genfromtxt('Index_exercise.txt', delimiter=',', dtype='int16')
print(indexexer)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [78]:
# Index the [11, 12] and [16, 17] values    
indexexer[2:4, 0:2]

array([[11, 12],
       [16, 17]], dtype=int16)

In [ ]:
# Index the 2, 8, 14, 20 values
indexexer[[0,1,2,3], [1,2,3,4]]

array([ 2,  8, 14, 20], dtype=int16)

In [82]:
# Index the 4,5, 34, 35, 39, 30 values
indexexer[[0,4,5], 3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]], dtype=int16)